# Generated by Django 3.2.7 on 2021-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csbok', '0002_rename_name_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
