# Generated by Django 3.2.7 on 2021-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csbok', '0004_alter_topic_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='abstract',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
