# Generated by Django 3.2.7 on 2021-09-07 12:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('csbok', '0005_topic_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
